# Generated by Django 4.0.4 on 2022-05-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema_sessions", "0002_tickets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickets",
            name="sold",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
