# Generated by Django 4.0.4 on 2022-05-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema_sessions", "0003_alter_tickets_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickets",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
