# Generated by Django 4.0.4 on 2022-05-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=110)),
            ],
            options={
                "verbose_name": "Actor",
                "verbose_name_plural": "Actors",
            },
        ),
        migrations.CreateModel(
            name="Genres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=110)),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=110)),
            ],
            options={
                "verbose_name": "Producer",
                "verbose_name_plural": "Producers",
            },
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("poster", models.ImageField(upload_to="posters/")),
                ("slug", models.SlugField(max_length=110)),
                ("description", models.TextField()),
                ("year", models.SmallIntegerField(default=2022)),
                ("duration", models.SmallIntegerField()),
                (
                    "age_rating",
                    models.CharField(
                        choices=[
                            ("G", "G"),
                            ("PG", "PG"),
                            ("PG-13", "PG-13"),
                            ("R", "R"),
                            ("NC-17", "NC-17"),
                        ],
                        max_length=5,
                    ),
                ),
                ("in_rental", models.BooleanField(default=True)),
                (
                    "actors",
                    models.ManyToManyField(related_name="movies", to="movies.actors"),
                ),
                (
                    "genres",
                    models.ManyToManyField(related_name="movies", to="movies.genres"),
                ),
                (
                    "producer",
                    models.ManyToManyField(related_name="movies", to="movies.producer"),
                ),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
            },
        ),
    ]
